#!/bin/bash

set -euo pipefail

extract_tarball() {
  rm -rf icu
  mkdir icu
  tar -xf dependency/*.tgz -C icu
}

set_ld_library_path() {
  export LD_LIBRARY_PATH="$PWD/icu/usr/local/lib:${LD_LIBRARY_PATH:-}"
}

check_version() {
  expected_version="${1}"
  actual_version="$(./icu/usr/local/bin/icuinfo 2>/dev/null | grep '"version"' | awk -F '[<>]' '{ print $3 }')"
  if [[ "${actual_version}" != "${expected_version}" ]]; then
    echo "Version ${actual_version} does not match expected version ${expected_version}"
    exit 1
  fi
}

main() {
  extract_tarball
  set_ld_library_path
  check_version "$1"

  echo "All tests passed!"
}

main "$@"
