version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: gomod
  directory: "/pkg/dependency/test/acceptance/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: gomod
  directory: "/actions/list-new-upstream-dependency-versions/entrypoint/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: gomod
  directory: "/actions/get-upstream-dependency/entrypoint/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
