#!/bin/bash

set -euo pipefail

extract_tarball() {
  rm -rf curl
  mkdir curl
  tar -xf dependency/*.tgz -C curl
}

set_ld_library_path() {
  export LD_LIBRARY_PATH="$PWD/curl/lib:${LD_LIBRARY_PATH:-}"
}

check_version() {
  expected_version=$1
  actual_version="$(./curl/bin/curl -V | head -n1 | awk '{ print $2 }')"
  if [[ "${actual_version}" != "${expected_version}" ]]; then
    echo "Version ${actual_version} does not match expected version ${expected_version}"
    exit 1
  fi
}

check_server() {
  output="$(mktemp)"
  if ! ./curl/bin/curl -fsS https://example.org > "${output}"; then
    cat "${output}"
    exit 1
  fi
}

main() {
  extract_tarball
  set_ld_library_path
  check_version "$1"
  check_server

  echo "All tests passed!"
}

main "$@"
