#!/bin/bash

set -euo pipefail

parent_dir="$(cd "$(dirname "$0")" && pwd)"

extract_tarball_pip() {
  rm -rf pip
  mkdir pip
  tar -xf dependency/*.tgz -C pip
}

extract_tarball_python() {
  rm -rf python
  mkdir python
  tar -xf required_dependency/*.tgz -C python
}

set_ld_library_path() {
  export LD_LIBRARY_PATH="$PWD/python/lib:${LD_LIBRARY_PATH:-}"
}

check_version() {
  expected_version="$1"
  actual_version="$(./python/bin/python ./pip/setup.py  --version)"
  if [[ "${actual_version}" != "${expected_version}" ]]; then
    echo "Version ${actual_version} does not match expected version ${expected_version}"
    exit 1
  fi
}

main() {
  extract_tarball_pip
  extract_tarball_python
  set_ld_library_path
  check_version "$1"

  echo "All tests passed!"
}

main "$@"
