name: 'Upload Dependency'
description: |
  Upload compiled dependency to AWS s3

inputs:
  bucket-name:
    description: AWS s3 bucket
    required: true
  dependency-name:
    description: Dependency name
    required: true
  artifact-path:
    description: Path to artifact
    required: true

outputs:
  dependency-uri:
    description: URI of uploaded dependency
    value: ${{ steps.upload.outputs.uri }}

runs:
  using: 'composite'
  steps:
    - id: upload
      shell: bash
      run: |
        #!/usr/bin/env bash
        set -euo pipefail

        filename="$(basename '${{ inputs.artifact-path }}')"

        aws s3 cp '${{ inputs.artifact-path }}' "s3://${{ inputs.bucket-name }}/deps/${{ inputs.dependency-name }}/${filename}"

        uri="https://deps.paketo.io/${{ inputs.dependency-name }}/${filename}"
        echo "uri=${uri}" >> "$GITHUB_OUTPUT"
