name: Deploy Dep-Server

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
    paths-ignore:
    - 'pkg/dependency/**'
    - '.github/workflows/test-dependency-library.yml'
    - '.github/workflows/generate-dependency-workflows.yml'
    - '.github/workflows/*-get-new-versions.yml'
    - '.github/workflows/*-build-upload.yml'
    - '.github/workflows/*-test-upload-metadata.yml'
    - '.github/templates/**'
    - '.github/data/**'

env:
  GAE_KEY: ${{ secrets.GAE_KEY }}
  GCP_PROJECT: ${{ secrets.GCP_PROJECT }}

jobs:
  deploy:
    name: Test
    runs-on: ubuntu-18.04
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_key: ${{ secrets.GAE_KEY }}
        project_id: ${{ secrets.GCP_PROJECT }}

    - name: Deploy Server
      run: gcloud app deploy --quiet
