name: Dotnet-sdk Build and Upload
"on":
  workflow_dispatch:
    inputs:
      VERSION:
        required: true
  repository_dispatch:
    types:
    - dotnet-sdk-build
env:
  DEP_NAME: dotnet-sdk
  VERSION: ${{ github.event.client_payload.data.version }}
jobs:
  build-upload:
    name: Build and Upload Dependency
    runs-on: ubuntu-18.04
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.18
    - name: Set Env Vars
      run: |
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
        fi
    - name: Get upstream dependency
      id: upstream
      uses: paketo-buildpacks/dep-server/actions/get-upstream-dependency@main
      with:
        name: ${{ env.DEP_NAME }}
        version: ${{ env.VERSION }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Modify CPE for Dispatch
      id: modify-cpe
      run: |
        cpe="$(echo '${{ steps.upstream.outputs.cpe }}' | sed 's|\\|\\\\|g')"
        echo "::set-output name=cpe::${cpe}"
    - name: Flatten Licenses
      id: flatten-licenses
      run: |
        licenses="$(echo '${{ steps.upstream.outputs.licenses }}' | sed -e 's/"//g' -e 's/[][]//g')"
        echo "::set-output name=licenses::${licenses}"
    - name: Trigger Tests
      uses: paketo-buildpacks/github-config/actions/dispatch@main
      with:
        repos: paketo-buildpacks/dep-server
        token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
        event: dotnet-sdk-test
        payload: |
          {
            "version": "${{ env.VERSION }}",
            "uri": "${{ steps.upstream.outputs.uri }}",
            "sha256": "${{ steps.upstream.outputs.sha256 }}",
            "source_uri": "${{ steps.upstream.outputs.uri }}",
            "source_sha256": "${{ steps.upstream.outputs.sha256 }}",
            "deprecation_date": "${{ steps.upstream.outputs.deprecation-date }}",
            "cpe": "${{ steps.modify-cpe.outputs.cpe }}",
            "purl": "${{ steps.upstream.outputs.purl }}",
            "licenses": "${{ steps.flatten-licenses.outputs.licenses }}"
          }
    - name: Notify Maintainers of Failures
      if: ${{ failure() }}
      uses: paketo-buildpacks/github-config/actions/issue/file@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repo: ${{github.repository}}
        label: workflow-failure
        comment_if_exists: true
        issue_title: Failed to Build/Upload ${{ env.DEP_NAME }}
        issue_body: '[Build and Upload workflow](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}) failed to run. Please take a look to ensure the version in the workflow is built and uploaded successfully. (cc @paketo-buildpacks/dependencies-maintainers)'
        comment_body: 'Another failure occurred: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}'
