name: Generate Dep Workflows

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
    paths:
    - '.github/templates/**'
    - '.github/data/**'
    - '.github/workflows/generate-dependency-workflows.yml'

jobs:
  generate-dep-workflows:
    runs-on: ubuntu-18.04
    steps:

    - name: Check out code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

    - name: Checkout Branch
      uses: paketo-buildpacks/github-config/actions/pull-request/checkout-branch@main
      with:
        branch: automation/dependency-workflows/update

    - name: Install dependencies
      run: |
        sudo curl -sSLf -o /usr/local/bin/yj https://github.com/sclevine/yj/releases/latest/download/yj-linux
        sudo chmod a+x /usr/local/bin/yj

        sudo curl -sSLf -o /usr/local/bin/ytt https://github.com/vmware-tanzu/carvel-ytt/releases/latest/download/ytt-linux-amd64
        sudo chmod a+x /usr/local/bin/ytt

    - name: Generate workflows
      run: |
        deps_json="$(cat .github/data/dependencies.yml | yj -yj)"
        deps="$(echo "$deps_json" | jq -r '.[].name')"

        for dep in $deps; do
          obj="$(echo "$deps_json" | jq -r ".[] | select( .name == \"$dep\")")"
          name="$(echo "${obj}" | jq -r ".name")"
          stacks="$(echo "${obj}" | jq -r '.stacks' -c)"
          mixins="$(echo "${obj}" | jq -r '.stacks[] | select( .id == "io.buildpacks.stacks.bionic").mixins // empty' -c)"
          requires="$(echo "${obj}" | jq -r '.requires // empty')"
          skip_test="$(echo "${obj}" | jq -r '.skip_test // false')"

          ytt \
            -f ".github/templates/get-new-versions.yml" \
            -f ".github/data/dependency-workflows-config.yml" \
            -v name="${name}" \
            > ".github/workflows/${name}-get-new-versions.yml"

          ytt \
            -f ".github/templates/build-upload.yml" \
            -f ".github/data/dependency-workflows-config.yml" \
            -v name="${name}" \
            > ".github/workflows/${name}-build-upload.yml"

          ytt \
            -f ".github/templates/test-upload-metadata.yml" \
            -f ".github/data/dependency-workflows-config.yml" \
            -v name="${name}" \
            -v stacks="${stacks}" \
            -v mixins="${mixins}" \
            -v required_dependency="${requires}" \
            -v skip_test="${skip_test}" \
            > ".github/workflows/${name}-test-upload-metadata.yml"
        done

    - name: Commit
      id: commit
      uses: paketo-buildpacks/github-config/actions/pull-request/create-commit@main
      with:
        message: "Update dependency workflows"
        pathspec: ".github/workflows/"
        keyid: ${{ secrets.PAKETO_BOT_GPG_SIGNING_KEY_ID }}
        key: ${{ secrets.PAKETO_BOT_GPG_SIGNING_KEY }}

    - name: Push Branch
      if: ${{ steps.commit.outputs.commit_sha != '' }}
      uses: paketo-buildpacks/github-config/actions/pull-request/push-branch@main
      with:
        branch: automation/dependency-workflows/update

    - name: Open Pull Request
      if: ${{ steps.commit.outputs.commit_sha != '' }}
      uses: paketo-buildpacks/github-config/actions/pull-request/open@main
      with:
        token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
        title: "Update dependency workflows"
        branch: automation/dependency-workflows/update
