name: Nginx Test and Upload Metadata
"on":
  repository_dispatch:
    types:
    - nginx-test
env:
  DEP_NAME: nginx
jobs:
  test-upload-metadata:
    name: Test Dependency and Upload Metadata
    runs-on: ubuntu-18.04
    steps:
    - name: Test
      uses: paketo-buildpacks/dep-server/actions/test-dependency@main
      with:
        name: ${{ env.DEP_NAME }}
        version: ${{ github.event.client_payload.version }}
        dependency_url: ${{ github.event.client_payload.uri }}
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Modify CPE for Upload
      id: modify-cpe
      run: |
        cpe="$(echo '${{ github.event.client_payload.cpe }}' | sed 's|\\|\\\\|g')"
        echo "::set-output name=cpe::${cpe}"
    - name: Convert Version to Semantic Version
      id: semantic-version
      uses: paketo-buildpacks/dep-server/actions/convert-semver@main
      with:
        version: ${{ github.event.client_payload.version }}
    - name: Upload dependency metadata
      uses: paketo-buildpacks/dep-server/actions/upload-metadata@main
      with:
        bucket-name: ${{ secrets.DEPS_BUCKET }}
        dependency-name: ${{ env.DEP_NAME }}
        version: ${{ steps.semantic-version.outputs.sem-version }}
        sha256: ${{ github.event.client_payload.sha256 }}
        uri: ${{ github.event.client_payload.uri }}
        stacks: '[{"id":"io.buildpacks.stacks.bionic"}]'
        source-uri: ${{ github.event.client_payload.source_uri }}
        source-sha256: ${{ github.event.client_payload.source_sha256 }}
        deprecation-date: ${{ github.event.client_payload.deprecation_date }}
        cpe: ${{ steps.modify-cpe.outputs.cpe }}
        purl: ${{ github.event.client_payload.purl }}
        licenses: ${{ github.event.client_payload.licenses }}
