name: Rust Test and Upload Metadata
"on":
  repository_dispatch:
    types:
    - rust-test
env:
  DEP_NAME: rust
jobs:
  test-upload-metadata:
    name: Test Dependency and Upload Metadata
    runs-on: ubuntu-18.04
    steps:
    - name: Test
      uses: paketo-buildpacks/dep-server/actions/test-dependency@main
      with:
        name: ${{ env.DEP_NAME }}
        version: ${{ github.event.inputs.version }}
        dependency_url: ${{ github.event.inputs.uri }}
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Modify CPE for Upload
      id: modify-cpe
      run: |
        cpe="$(echo '${{ github.event.inputs.cpe }}' | sed 's|\\|\\\\|g')"
        echo "::set-output name=cpe::${cpe}"
    - name: Upload dependency metadata
      uses: paketo-buildpacks/dep-server/actions/upload-metadata@main
      with:
        bucket-name: ${{ secrets.DEPS_BUCKET }}
        dependency-name: ${{ env.DEP_NAME }}
        version: ${{ github.event.inputs.version }}
        sha256: ${{ github.event.inputs.sha256 }}
        uri: ${{ github.event.inputs.uri }}
        stacks: '[{"id":"io.buildpacks.stacks.bionic"},{"id":"io.paketo.stacks.tiny"}]'
        source-uri: ${{ github.event.inputs.source_uri }}
        source-sha256: ${{ github.event.inputs.source_sha256 }}
        deprecation-date: ${{ github.event.inputs.deprecation_date }}
        cpe: ${{ steps.modify-cpe.outputs.cpe }}
        licenses: '{{ github.event.inputs.licenses }}'
