name: Test Dependency Library

on:
  workflow_dispatch: {}
  pull_request:
    branches: [ main ]
    paths:
    - 'pkg/dependency/**'
    - '.github/workflows/test-dependency-library.yml'

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16

    - name: Check out code
      uses: actions/checkout@v2

    - name: Run tests
      run: cd pkg/dependency && go test ./...

    - name: Run acceptance tests
      run: cd pkg/dependency/test/acceptance && go test ./...
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  approve:
    name: Auto Approve
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Approve
      uses: paketo-buildpacks/github-config/actions/pull-request/approve@main
      with:
        token: ${{ secrets.PAKETO_BOT_REVIEWER_GITHUB_TOKEN }}
        number: ${{ github.event.number }}
